### Rest Client Extension ###

@baseUrl = http://localhost:8080
@token = 
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "username",
    "password": "12345"
}

###

GET {{baseUrl}}/users
Authorization: Bearer {{token}}

###

POST {{baseUrl}}/register
Content-Type: application/json

{
    "UserName": "username",
    "Password": "12345",
    "IsAdmin" : true
}

###